#WEB SERVER PROFILES
# SPRING PROFILES
spring:         
    # DATASOURCE  
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url:  jdbc:mysql://182.254.212.213:3306/atblog?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: atecher
        password: hhw840129
        filters: stat,wall
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    freemarker:
       allow-request-override: false
       cache: true
       check-template-location: true
       charset: UTF-8
       content-type: text/html
       expose-request-attributes: true
       expose-session-attributes: true
       expose-spring-macro-helpers: true
       request-context-attribute: request
       suffix: .ftl
       template-loader-path: classpath:/templates/
    lucene:
       index-path: /app/lucene/index
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.atecher.blog.model
server:
  port: 80

